// Generated by gencpp from file lidar_msgs/VelodyneScan.msg
// DO NOT EDIT!


#ifndef LIDAR_MSGS_MESSAGE_VELODYNESCAN_H
#define LIDAR_MSGS_MESSAGE_VELODYNESCAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <lidar_msgs/VelodynePacket.h>

namespace lidar_msgs
{
template <class ContainerAllocator>
struct VelodyneScan_
{
  typedef VelodyneScan_<ContainerAllocator> Type;

  VelodyneScan_()
    : header()
    , packets()  {
    }
  VelodyneScan_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , packets(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::lidar_msgs::VelodynePacket_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::lidar_msgs::VelodynePacket_<ContainerAllocator> >> _packets_type;
  _packets_type packets;





  typedef boost::shared_ptr< ::lidar_msgs::VelodyneScan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_msgs::VelodyneScan_<ContainerAllocator> const> ConstPtr;

}; // struct VelodyneScan_

typedef ::lidar_msgs::VelodyneScan_<std::allocator<void> > VelodyneScan;

typedef boost::shared_ptr< ::lidar_msgs::VelodyneScan > VelodyneScanPtr;
typedef boost::shared_ptr< ::lidar_msgs::VelodyneScan const> VelodyneScanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_msgs::VelodyneScan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_msgs::VelodyneScan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lidar_msgs::VelodyneScan_<ContainerAllocator1> & lhs, const ::lidar_msgs::VelodyneScan_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.packets == rhs.packets;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lidar_msgs::VelodyneScan_<ContainerAllocator1> & lhs, const ::lidar_msgs::VelodyneScan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lidar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lidar_msgs::VelodyneScan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_msgs::VelodyneScan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_msgs::VelodyneScan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_msgs::VelodyneScan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_msgs::VelodyneScan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_msgs::VelodyneScan_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_msgs::VelodyneScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "959ef76e31922a901758298cc4ccbba3";
  }

  static const char* value(const ::lidar_msgs::VelodyneScan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x959ef76e31922a90ULL;
  static const uint64_t static_value2 = 0x1758298cc4ccbba3ULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_msgs::VelodyneScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_msgs/VelodyneScan";
  }

  static const char* value(const ::lidar_msgs::VelodyneScan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_msgs::VelodyneScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Velodyne LIDAR scan packets.\n"
"\n"
"std_msgs/Header    header\n"
"VelodynePacket[]   packets\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: lidar_msgs/VelodynePacket\n"
"# Raw Velodyne LIDAR packet.\n"
"\n"
"std_msgs/Time   stamp\n"
"uint8[1206]     data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Time\n"
"time data\n"
;
  }

  static const char* value(const ::lidar_msgs::VelodyneScan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_msgs::VelodyneScan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.packets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelodyneScan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_msgs::VelodyneScan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_msgs::VelodyneScan_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "packets[]" << std::endl;
    for (size_t i = 0; i < v.packets.size(); ++i)
    {
      s << indent << "  packets[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::lidar_msgs::VelodynePacket_<ContainerAllocator> >::stream(s, indent + "    ", v.packets[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_MSGS_MESSAGE_VELODYNESCAN_H
